---
name: Build Dev Artifact

on:
  push:
    branches:
      - 'master'
      - 'dev'
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - uses: actions/checkout@v4
      - run: make dev
      - uses: actions/upload-artifact@v4
        with:
          name: linux_x64
          path: ${{ github.workspace }}/bin/noisetorch
